//! Endgame tablebase (EGTB) — retrograde analysis for Songo (Mgpwem).
//!
//! The EGTB assigns an exact outcome (WIN / LOSS / DRAW) to every reachable
//! position with ≤ N_MAX seeds in play, by retrograde fixed-point iteration
//! over layers ordered by `seeds_in_play`. Captures strictly decrease
//! `seeds_in_play`, so retrograde starts at N=0 (fully captured, terminal)
//! and proceeds upward. Non-capture moves stay in the same layer and
//! require within-layer fixed-point iteration.
//!
//! # Scope of the current implementation
//!
//! - Covers **non-solidarity** positions. Solidarity states (isSolidarityMode=true)
//!   are rare and are left to be resolved at runtime by the NN+MCTS layer.
//! - Variant is fixed to Gabon (winning score 36). A parallel table for
//!   Cameroon (40) can be generated by passing a different winning score.
//! - Storage is in-memory (`HashMap<Index, Wdl>`) for the MVP. The M2.5
//!   follow-up will add CHD perfect-hash + zstd persistence to disk.

pub mod rank;
pub mod solver;
pub mod storage;

pub use rank::{Binomials, Index, board_count, position_count, rank_position, unrank_position};
pub use solver::{EgtbSolver, EgtbTable, Wdl};
pub use storage::{LayerData, LayerIoError};
